apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  tls:
    - hosts:
        - data-profiling.lab.sspcloud.fr
  rules:
    - host:  data-profiling.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: data-profiling-service
                port:
                  number: 80